FROM node:14-alpine as builder

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY ./package*.json ./
RUN npm install --silent
COPY . ./
RUN npm run build-dev

FROM nginx:1.17-alpine
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
EXPOSE 5050
CMD ["nginx", "-g", "daemon off;"]