name: CI

on:
  push:
    branches: [ develop, master, ci ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test:ci

      - name: Build for dev
        run: npm run build-dev
        if: contains(github.ref, 'develop') || contains(github.ref, 'ci')

      - name: Build for prod
        run: npm run build-prod
        if: contains(github.ref, 'master')

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build and push the Docker image for develop env
        run: |
          docker build -f ./Dockerfile.dev --tag ${{secrets.DOCKER_USERNAME}}/side-pool-frontend:dev .
          docker push ${{secrets.DOCKER_USERNAME}}/side-pool-frontend:dev
        if: contains(github.ref, 'develop') || contains(github.ref, 'ci')

      - name: Build and push the Docker image for production env
        run: |
          docker build --tag ${{secrets.DOCKER_USERNAME}}/side-pool-frontend:prod .
          docker push ${{secrets.DOCKER_USERNAME}}/side-pool-frontend:prod
        if: contains(github.ref, 'master')
